mcp_port: 15720

plugins:
  asr:
    enabled: false

  tts:
    enabled: true
    model_dir: /models/vits2-mix
    trt_dir: /models/vits2-mix/trt_i128
    model_type: "i128"
    speaker_id: 0
    speed: 1.0

  htmsg:
    enabled: false

  vop:
    enabled: false
